### ISSUE TITLE
Weird paths

### ISSUE THREAD

**Issue by GGORG0** [Assassin-1234/discord-wrapped#7]
1. When I put the folder in another one named `discord-wrapped`, it doesn't work.
```
$ pwd
/home/ggorg/Downloads/discord-wrapped/discord-wrapped

$ node .
running
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/ggorg/Downloads/discord-wrapped/package/account/user.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getUserInfo (/home/ggorg/Downloads/discord-wrapped/discord-wrapped/src/extractor/extract.js:170:28)
    at module.exports (/home/ggorg/Downloads/discord-wrapped/discord-wrapped/src/animations/wrap.js:91:21)
    at /home/ggorg/Downloads/discord-wrapped/discord-wrapped/index.js:4:8
    at Object.<anonymous> (/home/ggorg/Downloads/discord-wrapped/discord-wrapped/index.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/ggorg/Downloads/discord-wrapped/package/account/user.json'
}

Node.js v19.6.0
```
Possible cause: https://github.com/Assassin-1234/discord-wrapped/blob/main/src/animations/wrap.js#L1-L2 + more (just fixing line 1 and 2 didn't fix it)
Possible fix: use [node/path](https://nodejs.org/api/path.html)'s `resolve()` and `join()` functions

2. Bad practice: just appending paths together hoping that slashes (`/`) line up
Possible fix: use [node/path](https://nodejs.org/api/path.html)'s  `join()` function

3. Bad practice: using forward slashes (`/`) on windows, which uses backslashes (`\`)
Possible fix: use [node/path](https://nodejs.org/api/path.html)'s  `join()` function

As much as I'd like to make a PR, the code is too complicated and messy so it would take me way too long.

**Comment by Iliannnn** [comment]
@face-hh look into it ty

**Comment by Assassin-1234** [comment]
it shouldnt be relevant. We're removing self-host support from the repository and adding generation through our website. The code would stay only for transparency purposes and contributions/bug fix PRs. Update will come later today.
